---
- hosts: all
  become: yes

  tasks:
    - name: Actualizar cache de paquetes APT
      apt:
        update_cache: yes
      tags:
        - web
        - monitoring

    - name: Instalar Nginx
      apt:
        name: nginx
        state: present
      tags:
        - web

    - name: Habilitar y arrancar Nginx
      service:
        name: nginx
        state: started
        enabled: yes
      tags:
        - web

    - name: Asegurar que exista el directorio raiz de Nginx
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        mode: "0755"
      tags:
        - web

    - name: Crear directorio para imagenes del sitio
      file:
        path: /var/www/html/img
        state: directory
        owner: www-data
        group: www-data
        mode: "0755"
      tags:
        - web

    - name: Copiar index.html del sitio estatico
      copy:
        src: files/index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: "0644"
      tags:
        - web

    - name: Copiar imagen del sitio
      copy:
        src: files/img/uao.png
        dest: /var/www/html/img/uao.png
        owner: www-data
        group: www-data
        mode: "0644"
      tags:
        - web

    - name: Instalar node exporter en web
      apt:
        name: prometheus-node-exporter
        state: present
      tags:
        - web

    - name: Asegurar que node exporter este habilitado y corriendo en web
      service:
        name: prometheus-node-exporter
        state: started
        enabled: yes
      tags:
        - web

    - name: Instalar Prometheus y node exporter en monitoring
      apt:
        name:
          - prometheus
          - prometheus-node-exporter
        state: present
      tags:
        - monitoring

    - name: Copiar configuracion de Prometheus
      copy:
        src: files/prometheus.yml
        dest: /etc/prometheus/prometheus.yml
        owner: root
        group: root
        mode: "0644"
      tags:
        - monitoring
      notify: Reiniciar Prometheus

    - name: Instalar dependencias para repos HTTPS y certificados
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - software-properties-common
          - wget
        state: present
        update_cache: yes
      tags:
        - monitoring

    - name: Agregar llave GPG de Grafana
      apt_key:
        url: https://apt.grafana.com/gpg.key
        state: present
      tags:
        - monitoring

    - name: Agregar repositorio APT de Grafana
      apt_repository:
        repo: "deb https://apt.grafana.com stable main"
        state: present
      tags:
        - monitoring

    - name: Actualizar cache de paquetes despues de agregar repo Grafana
      apt:
        update_cache: yes
      tags:
        - monitoring

    - name: Instalar Grafana
      apt:
        name: grafana
        state: present
      tags:
        - monitoring

    - name: Habilitar y arrancar servicios Prometheus y Grafana
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - prometheus
        - grafana-server
      tags:
        - monitoring

  handlers:
    - name: Reiniciar Prometheus
      service:
        name: prometheus
        state: restarted